// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh-0hszbRhKECJ2QBnsALlhYQg-FoGLkA',
    appId: '1:15510839196:web:8c9f68525021630e4ef259',
    messagingSenderId: '15510839196',
    projectId: 'canacache',
    authDomain: 'canacache.firebaseapp.com',
    storageBucket: 'canacache.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA57gnVWuYK7XnhCb7mRFkHq3KJlCwhA9A',
    appId: '1:15510839196:android:59c96c14cd3ec3f54ef259',
    messagingSenderId: '15510839196',
    projectId: 'canacache',
    storageBucket: 'canacache.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcyvTP-WB60GaTNeldjnQyqIhzVcYuS7c',
    appId: '1:15510839196:ios:6e200f46ca6a1a344ef259',
    messagingSenderId: '15510839196',
    projectId: 'canacache',
    storageBucket: 'canacache.appspot.com',
    iosClientId: '15510839196-ipb3a418aq6uc45lvos7tls4hpeib465.apps.googleusercontent.com',
    iosBundleId: 'com.canacache',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcyvTP-WB60GaTNeldjnQyqIhzVcYuS7c',
    appId: '1:15510839196:ios:6e200f46ca6a1a344ef259',
    messagingSenderId: '15510839196',
    projectId: 'canacache',
    storageBucket: 'canacache.appspot.com',
    iosClientId: '15510839196-ipb3a418aq6uc45lvos7tls4hpeib465.apps.googleusercontent.com',
    iosBundleId: 'com.canacache',
  );
}
