// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import "package:flutter/foundation.dart"
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for windows - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for linux - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      default:
        throw UnsupportedError(
          "DefaultFirebaseOptions are not supported for this platform.",
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBweQ3l5objrgIETKwV5mcA1kVFGlPZ9_s",
    appId: "1:595543031932:web:3e8a3440f42977438cc9f9",
    messagingSenderId: "595543031932",
    projectId: "cana-cache",
    authDomain: "cana-cache.firebaseapp.com",
    storageBucket: "cana-cache.appspot.com",
    measurementId: "G-L5N4RJNXYR",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyCN1W98gKF9LgJqFMYVGW5IK9utnng6B4I",
    appId: "1:595543031932:android:d78ec37984f723a78cc9f9",
    messagingSenderId: "595543031932",
    projectId: "cana-cache",
    storageBucket: "cana-cache.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyCpaGsBu8Y8dm4kIXixCdDV_tWCPIGYc7w",
    appId: "1:595543031932:ios:f41f7910adf488b48cc9f9",
    messagingSenderId: "595543031932",
    projectId: "cana-cache",
    storageBucket: "cana-cache.appspot.com",
    iosClientId:
        "595543031932-rasdnetp2t8g9ocj37kvoav357kp8tge.apps.googleusercontent.com",
    iosBundleId: "com.canacache",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyCpaGsBu8Y8dm4kIXixCdDV_tWCPIGYc7w",
    appId: "1:595543031932:ios:f41f7910adf488b48cc9f9",
    messagingSenderId: "595543031932",
    projectId: "cana-cache",
    storageBucket: "cana-cache.appspot.com",
    iosClientId:
        "595543031932-rasdnetp2t8g9ocj37kvoav357kp8tge.apps.googleusercontent.com",
    iosBundleId: "com.canacache",
  );
}
